/******************************************************************************
 *
 * Copyright (c) 2014  Haixing Hu
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/

package com.github.haixing_hu.csl;

import static com.github.haixing_hu.csl.VariableType.*;

/**
 * The enumeration of variables.
 *
 * @see <a href='http://citationstyles.org/downloads/specification.html#appendix-iv-variables'>Variables</a>
 * @author Haixing Hu
 */
public enum Variable {

  /**
   * The abstract of the item (e.g. the abstract of a journal article).
   */
  ABSTRACT("abstract", STRING),

  /**
   * The date the item has been accessed.
   */
  ACCESSED("accessed", DATE),

  /**
   * The reader's notes about the item content.
   */
  ANNOTE("annote", STRING),

  /**
   * The archive storing the item.
   */
  ARCHIVE("archive", STRING),

  /**
   * The storage location within an archive (e.g. a box and folder number).
   */
  ARCHIVE_LOCATION("archive_location", STRING),

  /**
   * The geographic location of the archive.
   */
  ARCHIVE_PLACE("archive-place", STRING),

  /**
   * The name of the author.
   */
  AUTHOR("author", NAME),

  /**
   * The issuing or judicial authority (e.g. "USPTO" for a patent, "Fairfax
   * Circuit Court" for a legal case).
   */
  AUTHORITY("authority", STRING),

  /**
   * The call number (to locate the item in a library).
   */
  CALL_NUMBER("call-number", STRING),

  /**
   * The chapter number.
   */
  CHAPTER_NUMBER("chapter-number", INTEGER),

  /**
   * The label identifying the item in in-text citations of label styles (e.g.
   * "Ferr78"). May be assigned by the CSL processor based on item metadata.
   */
  CITATION_LABEL("citation-label", STRING),

  /**
   * The index (starting at 1) of the cited reference in the bibliography
   * (generated by the CSL processor).
   */
  CITATION_NUMBER("citation-number", STRING),

  /**
   * The name of the editor of the collection holding the item (e.g. the series
   * editor for a book).
   */
  COLLECTION_EDITOR("collection-editor", NAME),

  /**
   * The number identifying the collection holding the item (e.g. the series
   * number for a book).
   */
  COLLECTION_NUMBER("collection-number", INTEGER),

  /**
   * The title of the collection holding the item (e.g. the series title for a
   * book).
   */
  COLLECTION_TITLE("collection-title", STRING),

  /**
   * The name of the composer (e.g. of a musical score).
   */
  COMPOSER("composer", NAME),

//  /**
//   * The container holding the item.
//   */
//  CONTAINER("container", DATE),

  /**
   * The name of the author of the container holding the item (e.g. the book
   * author for a book chapter).
   */
  CONTAINER_AUTHOR("container-author", NAME),

  /**
   * The title of the container holding the item (e.g. the book title for a
   * book chapter, the journal title for a journal article).
   */
  CONTAINER_TITLE("container-title", STRING),

  /**
   * The short/abbreviated form of "container-title" (also accessible through
   * the "short" form of the "container-title" variable)
   */
  CONTAINER_TITLE_SHORT("container-title-short", STRING),

  /**
   * The physical (e.g. size) or temporal (e.g. running time) dimensions of the
   * item.
   */
  DIMENSIONS("dimensions", STRING),

  /**
   * The name of the director (e.g. of a film).
   */
  DIRECTOR("director", NAME),

  /**
   * The Digital Object Identifier (e.g. "10.1128/AEM.02591-07").
   */
  DOI("DOI", STRING),

  /**
   * The (container) edition holding the item (e.g. "3" when citing a chapter
   * in the third edition of a book).
   */
  EDITION("edition", INTEGER),

  /**
   * The name of the editor.
   */
  EDITOR("editor", NAME),

  /**
   * The name of the managing editor ("Directeur de la Publication" in French).
   */
  EDITORIAL_DIRECTOR("editorial-director", NAME),

  /**
   * The name of the related event (e.g. the conference name when citing a
   * conference paper).
   */
  EVENT("event", STRING),

  /**
   * The date the related event took place.
   */
  EVENT_DATE("event-date", DATE),

  /**
   * The geographic location of the related event (e.g. "Amsterdam, the
   * Netherlands").
   */
  EVENT_PLACE("event-place", STRING),

  /**
   * The number of a preceding note containing the first reference to the item.
   * <p>
   * Assigned by the CSL processor. The variable holds no value for
   * non-note-based styles, or when the item hasn't been cited in any preceding
   * notes.
   */
  FIRST_REFERENCE_NOTE_NUMBER("first-reference-note-number", STRING),

  /**
   * The class, type or genre of the item (e.g. "adventure" for an adventure
   * movie, "PhD dissertation" for a PhD thesis).
   */
  GENRE("genre", STRING),

  /**
   * The name of the illustrator (e.g. of a children's book).
   */
  ILLUSTRATOR("illustrator", NAME),

  /**
   * The name of the interviewer (e.g. of an interview).
   */
  INTERVIEWER("interviewer", NAME),

  /**
   * The International Standard Book Number.
   */
  ISBN("ISBN", STRING),

  /**
   * The International Standard Serial Number.
   */
  ISSN("ISSN", STRING),

  /**
   * The (container) issue holding the item (e.g. "5" when citing a journal
   * article from journal volume 2, issue 5).
   */
  ISSUE("issue", INTEGER),

  /**
   * The date the item was issued/published.
   */
  ISSUED("issued", DATE),

  /**
   * The geographic scope of relevance (e.g. "US" for a US patent).
   */
  JURISDICTION("jurisdiction", STRING),

  /**
   * The keyword(s) or tag(s) attached to the item.
   */
  KEYWORD("keyword", STRING),

  /**
   * A cite-specific pinpointer within the item (e.g. a page number within a
   * book, or a volume in a multi-volume work).
   * <p>
   * Must be accompanied in the input data by a label indicating the locator
   * type (see the Locators term list), which determines which term is rendered
   * by cs:label when the "locator" variable is selected.
   */
  LOCATOR("locator", STRING),

  /**
   * The medium description (e.g. "CD", "DVD", etc.).
   */
  MEDIUM("medium", STRING),

  /**
   * The (short) inline note giving additional item details (e.g. a concise
   * summary or commentary).
   */
  NOTE("note", STRING),

  /**
   * The number identifying the item (e.g. a report number).
   */
  NUMBER("number", INTEGER),

  /**
   * The total number of pages of the cited item.
   */
  NUMBER_OF_PAGES("number-of-pages", INTEGER),

  /**
   * The total number of volumes, usable for citing multi-volume books and such.
   */
  NUMBER_OF_VOLUMES("number-of-volumes", INTEGER),

  /**
   * The name of the author of the original version.
   */
  ORIGINAL_AUTHOR("original-author", NAME),

  /**
   * The (issue) date of the original version.
   */
  ORIGINAL_DATE("original-date", DATE),

  /**
   * The original publisher, for items that have been republished by a different
   * publisher.
   */
  ORIGINAL_PUBLISHER("original-publisher", STRING),

  /**
   * The geographic location of the original publisher (e.g. "London, UK").
   */
  ORIGINAL_PUBLISHER_PLACE("original-publisher-place", STRING),

  /**
   * The title of the original version (e.g. "Война и мир", the untranslated
   * Russian title of "War and Peace").
   */
  ORIGINAL_TITLE("original-title", STRING),

  /**
   * The range of pages the item (e.g. a journal article) covers in a container
   * (e.g. a journal issue).
   */
  PAGE("page", STRING),

  /**
   * The first page of the range of pages the item (e.g. a journal article)
   * covers in a container (e.g. a journal issue).
   */
  PAGE_FIRST("page-first", STRING),

  /**
   * The PubMed Central reference number.
   */
  PMCID("PMCID", STRING),

  /**
   * The PubMed reference number.
   */
  PMID("PMID", STRING),

  /**
   * The publisher.
   */
  PUBLISHER("publisher", STRING),

  /**
   * The geographic location of the publisher.
   */
  PUBLISHER_PLACE("publisher-place", STRING),

  /**
   * The name of recipient (e.g. of a letter).
   */
  RECIPIENT("recipient", NAME),

  /**
   * The resources related to the procedural history of a legal case.
   */
  REFERENCES("references", STRING),

  /**
   * The name of the author of the item reviewed by the current item.
   */
  REVIEWED_AUTHOR("reviewed-author", NAME),

  /**
   * The title of the item reviewed by the current item.
   */
  REVIEWED_TITLE("reviewed-title", STRING),

  /**
   * The scale of e.g. a map.
   */
  SCALE("scale", STRING),

  /**
   * The container section holding the item (e.g. "politics" for a newspaper
   * article).
   */
  SECTION("section", STRING),

  /**
   * Indicates from whence the item originates (e.g. a library catalog or
   * database).
   */
  SOURCE("source", STRING),

  /**
   * The (publication) status of the item (e.g. "forthcoming").
   */
  STATUS("status", STRING),

  /**
   * The date the item (e.g. a manuscript) has been submitted for publication.
   */
  SUBMITTED("submitted", DATE),

  /**
   * The primary title of the item.
   */
  TITLE("title", STRING),

  /**
   * The short/abbreviated form of "title" (also accessible through the "short"
   * form of the "title" variable).
   */
  TITLE_SHORT("title-short", STRING),

  /**
   * The name of the translator.
   */
  TRANSLATOR("translator", NAME),

  /**
   * The Uniform Resource Locator (e.g. "http://aem.asm.org/cgi/content/full/74/9/2766").
   */
  URL("URL", STRING),

  /**
   * The version of the item (e.g. "2.0.9" for a software program).
   */
  VERSION("version", STRING),

  /**
   * The (container) volume holding the item (e.g. "2" when citing a chapter
   * from book volume 2).
   */
  VOLUME("volume", INTEGER),

  /**
   * The disambiguating year suffix in author-date styles (e.g. "a" in "Doe, 1999a").
   */
  YEAR_SUFFIX("year-suffix", STRING);

  private final String name;
  private final VariableType type;

  private Variable(String name, VariableType type) {
    this.name = name;
    this.type = type;
  }

  /**
   * Gets the standard name of this variable.
   *
   * @return the standard name of this variable.
   */
  public String getName() {
    return name;
  }

  /**
   * Gets the data type of values of this variable.
   *
   * @return the data type of values of this variable.
   */
  public VariableType getType() {
    return type;
  }
}
